import time
import requests

requests.get('http://pihub.local:5000/lightoff')
requests.get('http://pihub.local:5000/outlets/off')
time.sleep(1)
requests.get('http://mini.local:5000/background/off')
time.sleep(.1)
requests.get('http://mini.local:5000/reverb/on')
time.sleep(.1)
#requests.get('http://mini.local:5000/spotify/pause')
requests.get('http://pihub.local:5000/setlight/0/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/1/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/2/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/3/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/4/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/5/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/6/color/blue/dim/10')
requests.get('http://pihub.local:5000/setlight/7/color/blue/dim/10')
requests.get('http://pihub.local:5000/fadein')
requests.get('http://pihub.local:5000/outlets/off')
requests.get('http://pihub.local:5000/play/jellyfish')
time.sleep(5)
#requests.get('http://pitwo.local:5000/play/jellyfish')
